// "use client"

// import { Inter } from "next/font/google";
// import "./globals.css";
// import Header from "../components/ui/Header";
// import Navbar from "@/components/ui/Navbar";
// import { CartProvider } from "./context/cartContext";
// import { Metadata } from 'next';  // Import Metadata from next




// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout  
// ({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
      
      
//       <Header/>

//       <CartProvider>
//       <Navbar />
      
     
      
//       {children}
      
//       </CartProvider>
      
//       </body>
//     </html>
//   );
// }


// File: src/app/layout.tsx

// 'use client' directive ko sirf client-side components ke liye rakhein
'use client';  

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/ui/Header";
import Navbar from "@/components/ui/Navbar";
import { CartProvider } from "use-shopping-cart";
import Footer from "@/components/ui/Footer";


const inter = Inter({ subsets: ["latin"] });

// **Client-Side Layout** - Isme aapka Header, CartProvider aur Navbar hote hain
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <CartProvider
      mode="payment"  // "client-only" | "payment" | "checkout-session"
      cartMode="client-only"  // Ensure this is the correct mode
      stripe={process.env.NEXT_PUBLIC_STRIPE_KEY}  // Stripe public key
      currency="USD"
      successUrl="/success"
      cancelUrl="/cancel"
      shouldPersist={true}  // Optional: to persist cart data across sessions
    >

    
        <Header />
       
          <Navbar />
          {children}

    </CartProvider>
    <Footer/>    


      </body>
    </html>
  );
}
